export const SESSION_TOKEN_LENGTH = 32;
export const SESSION_TTL_DAYS = 30;

export const LOGIN_MAX_ATTEMPTS = 5;
export const LOGIN_WINDOW_SECONDS = 60;

export const SESSION_CACHE_TTL_SECONDS = 60;
export const MAX_ACTIVE_SESSIONS_PER_USER = 10;

export const VERIFICATION_CODE_TTL_SECONDS = 10 * 60;
export const VERIFICATION_RESEND_COOLDOWN_SECONDS = 60;
export const VERIFICATION_MAX_ATTEMPTS = 10;
export const VERIFICATION_ATTEMPTS_WINDOW_SECONDS = 10 * 60;
